modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]] 
modId="nuclearcraft" 
version="${file.jarVersion}" 
displayName="Nuclearcraft Neoteric" 
logoFile="logo.png"
credits="tomdodd4598"
authors="igentuman"
description='''
A complex nuclear engineering mod for Minecraft
'''

[[dependencies.nuclearcraft]]
modId="forge" 
mandatory=true 
versionRange="[37,)"
ordering="NONE"
side="BOTH"
[[dependencies.nuclearcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,)"
ordering="NONE"
side="BOTH"
